variable "HTC_POC_OP_618580_APIGateway_Execution_ARN" {}
variable "HTC_POC_OP_618580_QueueSQS_Name" {}
variable "HTC_POC_OP_618580_QueueSQS_DelaySeconds" {}
variable "HTC_POC_OP_618580_QueueSQS_MaxMessageSize" {}
variable "HTC_POC_OP_618580_QueueSQS_MessageRetentionSeconds" {}
variable "HTC_POC_OP_618580_QueueSQS_VisisbilityTimeoutSeconds" {}
variable "HTC_POC_OP_618580_QueueSQS_ReceiveWaitTimeSeconds" {}
variable "HTC_POC_OP_618580_QueueSQS_ARN" {}
variable "common_tags" {}
