variable "Usecase_APIGateway_Execution_ARN" {}
variable "Usecase_QueueSQS_Name" {}
variable "Usecase_QueueSQS_DelaySeconds" {}
variable "Usecase_QueueSQS_MaxMessageSize" {}
variable "Usecase_QueueSQS_MessageRetentionSeconds" {}
variable "Usecase_QueueSQS_VisisbilityTimeoutSeconds" {}
variable "Usecase_QueueSQS_ReceiveWaitTimeSeconds" {}
variable "Usecase_QueueSQS_ARN" {}
variable "common_tags" {}
