variable "HTC_POC_OP_618580_QueueSQS_ARN" {}
variable "HTC_POC_OP_618580_LambdaRoleForAuthorizer_ARN" {}
variable "HTC_POC_OP_618580_QueueSQS" {}
variable "HTC_POC_OP_618580_QueueSQS_URL" {}
variable "HTC_POC_OP_618580_DynamoDBTable_Name" {}
variable "HTC_POC_OP_618580_LambdaFunction_CRUD_FileName" {}
variable "HTC_POC_OP_618580_LambdaFunction_CRUD_FunctionName" {}
variable "HTC_POC_OP_618580_LambdaFunction_CRUD_Handler" {}
variable "HTC_POC_OP_618580_LambdaFunction_Runtime" {}
variable "HTC_POC_OP_618580_LambdaFunction_GET_FileName" {}
variable "HTC_POC_OP_618580_LambdaFunction_GET_FunctionName" {}
variable "HTC_POC_OP_618580_LambdaFunction_GET_Handler" {}
variable "HTC_POC_OP_618580_LambdaTokenAuthorizer_FileName" {}
variable "HTC_POC_OP_618580_LambdaTokenAuthorizer_FunctionName" {}
variable "HTC_POC_OP_618580_LambdaTokenAuthorizer_Handler" {}
variable "HTC_POC_OP_618580_LambdaTrigger_BatchSize" {}
variable "HTC_POC_OP_618580_LambdaTrigger_MaximumBatchingWindowInSeconds" {}
variable "HTC_POC_OP_618580_LambdaRole_ARN" {}
variable "HTC_POC_OP_618580_LambdaFunction_CRUD_FileName_archives" {}
variable "HTC_POC_OP_618580_LambdaFunction_GET_FileName_archives" {}
variable "HTC_POC_OP_618580_LambdaTokenAuthorizer_FileName_archives" {}
variable "HTC_POC_OP_618580_LambdaFunction_CRUD_Archive" {}
variable "HTC_POC_OP_618580_LambdaFunction_GET_Archive" {}
variable "HTC_POC_OP_618580_LambdaTokenAuthorizer_Archive" {}
variable "common_tags" {}
