variable "Usecase_QueueSQS_ARN" {}
variable "Usecase_LambdaRoleForAuthorizer_ARN" {}
variable "Usecase_QueueSQS" {}
variable "Usecase_QueueSQS_URL" {}
variable "Usecase_DynamoDBTable_Name" {}
variable "Usecase_LambdaFunction_CRUD_FileName" {}
variable "Usecase_LambdaFunction_CRUD_FunctionName" {}
variable "Usecase_LambdaFunction_CRUD_Handler" {}
variable "Usecase_LambdaFunction_Runtime" {}
variable "Usecase_LambdaFunction_GET_FileName" {}
variable "Usecase_LambdaFunction_GET_FunctionName" {}
variable "Usecase_LambdaFunction_GET_Handler" {}
variable "Usecase_LambdaTokenAuthorizer_FileName" {}
variable "Usecase_LambdaTokenAuthorizer_FunctionName" {}
variable "Usecase_LambdaTokenAuthorizer_Handler" {}
variable "Usecase_LambdaTrigger_BatchSize" {}
variable "Usecase_LambdaTrigger_MaximumBatchingWindowInSeconds" {}
variable "Usecase_LambdaRole_ARN" {}
variable "Usecase_LambdaFunction_CRUD_FileName_archives" {}
variable "Usecase_LambdaFunction_GET_FileName_archives" {}
variable "Usecase_LambdaTokenAuthorizer_FileName_archives" {}
variable "Usecase_LambdaFunction_CRUD_Archive" {}
variable "Usecase_LambdaFunction_GET_Archive" {}
variable "Usecase_LambdaTokenAuthorizer_Archive" {}
variable "common_tags" {}
