variable "Usecase_LambdaTokenAuthorizer_InvokeARN" {}
variable "Usecase_LambdaFunction_GET_FunctionName" {}
variable "Usecase_LambdaFunction_GET_ARN" {}
variable "Usecase_LambdaTokenAuthorizer_Name" {}
variable "Usecase_LambdaTokenAuthorizer_Type" {}
variable "Usecase_LambdaTokenAuthorizer_IdentitySource" {}
variable "Usecase_APIGateway_Name" {}
variable "Usecase_APIGateway_Description" {}
variable "Usecase_APIGateway_EndpointType" {}
variable "Usecase_APIGateway_Resource_PathPart" {}
variable "Usecase_APIGateway_RequestValidator_Name" {}
variable "Usecase_APIGateway_RequestValidator_ValidateRequestBody" {}
variable "Usecase_APIGateway_HTTPMETHOD" {}
variable "Usecase_APIGateway_Method_Authorization" {}
variable "Usecase_APIGateway_Integration_TYPE" {}
variable "Usecase_APIGateway_Integration_RequestTemplates" {}
variable "Usecase_APIGateway_Integration_RequestParameters" {}
variable "Usecase_APIGateway_IntegrationResponse_Post_ResponseTemplate" {}
variable "Usecase_APIGateway_IntegrationResponse_PUT_ResponseTemplate" {}
variable "Usecase_APIGateway_MethodResponse_DELETE_ResponseTemplate" {}
variable "Usecase_APIGateway_MethodResponse_StatusCode" {}
variable "Usecase_APIGateway_Method_PUT_HttpMethod" {}
variable "Usecase_APIGateway_Method_DELETE_HttpMethod" {}
variable "Usecase_APIGateway_Invoke_GET_StatementID" {}
variable "Usecase_APIGateway_Invoke_GET_Action" {}
variable "Usecase_APIGateway_Invoke_GET_Principle" {}
variable "Usecase_Method_GET_HttpMethod" {}
variable "Usecase_Integration_GET_Type" {}
variable "Usecase_Integration_GET_ApplicationJson" {}
variable "Usecase_MethodResponse_GET_ResponseModels" {}
variable "Usecase_IntegrationResponse_GET_ResponseTemplate" {}
variable "Usecase_APIGatewayDeployment_StageName" {}
variable "arn_apigateway" {}
variable "Usecase_QueueSQS_path" {}
variable "aws_account" {}
variable "Usecase_LambdaRoleForAuthorizer_ARN" {}
variable "Usecase_APIGatewayRole_ARN" {}
variable "common_tags" {}
