variable "HTC_POC_OP_618580_LambdaTokenAuthorizer_InvokeARN" {}
variable "HTC_POC_OP_618580_LambdaFunction_GET_FunctionName" {}
variable "HTC_POC_OP_618580_LambdaFunction_GET_ARN" {}
variable "HTC_POC_OP_618580_LambdaTokenAuthorizer_Name" {}
variable "HTC_POC_OP_618580_LambdaTokenAuthorizer_Type" {}
variable "HTC_POC_OP_618580_LambdaTokenAuthorizer_IdentitySource" {}
variable "HTC_POC_OP_618580_APIGateway_Name" {}
variable "HTC_POC_OP_618580_APIGateway_Description" {}
variable "HTC_POC_OP_618580_APIGateway_EndpointType" {}
variable "HTC_POC_OP_618580_APIGateway_Resource_PathPart" {}
variable "HTC_POC_OP_618580_APIGateway_RequestValidator_Name" {}
variable "HTC_POC_OP_618580_APIGateway_RequestValidator_ValidateRequestBody" {}
variable "HTC_POC_OP_618580_APIGateway_HTTPMETHOD" {}
variable "HTC_POC_OP_618580_APIGateway_Method_Authorization" {}
variable "HTC_POC_OP_618580_APIGateway_Integration_TYPE" {}
variable "HTC_POC_OP_618580_APIGateway_Integration_RequestTemplates" {}
variable "HTC_POC_OP_618580_APIGateway_Integration_RequestParameters" {}
variable "HTC_POC_OP_618580_APIGateway_IntegrationResponse_Post_ResponseTemplate" {}
variable "HTC_POC_OP_618580_APIGateway_IntegrationResponse_PUT_ResponseTemplate" {}
variable "HTC_POC_OP_618580_APIGateway_MethodResponse_DELETE_ResponseTemplate" {}
variable "HTC_POC_OP_618580_APIGateway_MethodResponse_StatusCode" {}
variable "HTC_POC_OP_618580_APIGateway_Method_PUT_HttpMethod" {}
variable "HTC_POC_OP_618580_APIGateway_Method_DELETE_HttpMethod" {}
variable "HTC_POC_OP_618580_APIGateway_Invoke_GET_StatementID" {}
variable "HTC_POC_OP_618580_APIGateway_Invoke_GET_Action" {}
variable "HTC_POC_OP_618580_APIGateway_Invoke_GET_Principle" {}
variable "HTC_POC_OP_618580_Method_GET_HttpMethod" {}
variable "HTC_POC_OP_618580_Integration_GET_Type" {}
variable "HTC_POC_OP_618580_Integration_GET_ApplicationJson" {}
variable "HTC_POC_OP_618580_MethodResponse_GET_ResponseModels" {}
variable "HTC_POC_OP_618580_IntegrationResponse_GET_ResponseTemplate" {}
variable "HTC_POC_OP_618580_APIGatewayDeployment_StageName" {}
variable "arn_apigateway" {}
variable "HTC_POC_OP_618580_QueueSQS_path" {}
variable "aws_account" {}
variable "HTC_POC_OP_618580_LambdaRoleForAuthorizer_ARN" {}
variable "HTC_POC_OP_618580_APIGatewayRole_ARN" {}
variable "common_tags" {}
